export const POPULAR_SEARCHES = [
    'Adidas',
    'Arrow',
    'Fila',
    'Online Shopping',
    'Nike',
    'Pepe Jeans',
    'Puma',
    'United Colors Of Benetton',
    'Fastrack',
    'Shorts',
    'Being Human',
    'Skirts',
    'Woodland',
    'Supra',
    'Dresses',
    'Clothing',
    'Jewellery',
    'T Shirts',
    'Shoes',
    'Bags',
    'Watches',
    'Caps',
    'Shirts',
    'Backpacks',
    'Flip Flops',
    'Sunglasses',
    'Kurtas',
    'Lingerie',
    'Jackets',
    'Skechers',
    'Saree',
    'Sandals',
    'Puma',
    'Tshirts',
    'Woodland Shoes',
    'Titan Watches',
    'Fastrack Watches',
    'Wrangler Shirts',
    'Adidas Tshirts',
    'Nike Shoes',
    'Roadster Shirts',
    'Casual Shoes',
    'Running Shoes',
    'Nike Sports Shoes',
    'Jeans',
    'Being Human Tshirts',
    'Converse Shoes',
    'Cricket Shoes'];

export const COLORS = ['Black (6218)'
    , 'White (5144)'
    , 'Blue (4213)'
    , 'Navy Blue (3903)'
    , 'Grey (2519)'
    , 'Red (1626)'
    , 'Grey Melange (1551)'
    , 'Olive (1243)'
    , 'Charcoal (1219)'
    , 'Green (1125)'
    , 'Maroon (981)'
    , 'Yellow (697)'
    , 'Off White (560)'
    , 'Orange (476)'
    , 'Pink (395)'
    , 'Mustard (378)'
    , 'Teal (377)'
    , 'Beige (276)'
    , 'Brown (257)'
    , 'Burgundy (255)'
    , 'Rust (245)'
    , 'Coral (189)'
    , 'Purple (177)'
    , 'Peach (151)'
    , 'Cream (147)'
    , 'Multi (142)'
    , 'Turquoise Blue (102)'
    , 'Sea Green (99)'
    , 'Khaki (62)'
    , 'Fluorescent Green (43)'
    , 'Lime Green (41)'
    , 'Taupe (37)'
    , 'Mauve (37)'
    , 'Coffee Brown (25)'
    , 'Lavender (22)'
    , 'Magenta (11)'
    , 'Nude (5)'
    , 'Tan (4)'
    , 'Rose (3)'
    , 'Bronze (2)'
    , 'Steel (1)'
    , 'Gold (1)'];

export const BRANDS = ['2GO(54)',
    '4F(2)',
    'ADIDAS(142)',
    'ADIDAS Originals(44)',
    'Alcis(26)',
    'Azani(15)',
    'ASICS(13)',
    'Aeropostale(13)',
    'AMERICAN EAGLE OUTFITTERS(12)',
    'Ajile by Pantaloons(8)',
    'Adobe(8)',
    'Avengers(7)',
    'ALCOTT(7)',
    'Allen Solly Sport(6)',
    'Adamo London(6)',
    'ACTIMAXX(6)',
    'ARISE(5)',
    'Aesthetic Bodies(5)',
    'Arrow Blue Jean Co.(4)',
    'Antony Morato(4)',
    'Austin wood(1)',
    'ASICS Tiger(1)',
    'Arrow New York(1)',
    'appulse(1)',
    'American Crew(1)',
    'Allen Solly(1)',
    'Blue Saint(36)',
    'Being Human(32)',
    'Blackberrys(26)',
    'Batman(26)',
    'Bushirt(22)',
    'Breakbounce(16)',
    'Bossini(9)',
    'Braveo(8)',
    'BLISTON(7)',
    'Blotch(6)',
    'Basics(3)',
    'BUKKUM(2)',
    'bigbanana(2)',
    'Besiva(2)',
    'Barcelona(2)',
    'BULLMER(1)',
    'Beer Studio(1)',
    'Beatles(1)',
    'Bar Harbour(1)',
    'Bamboo Tribe(1)',
    'Calvin Klein Jeans(103)',
    'Campus Sutra(71)',
    'Celio(24)',
    'Club York(18)',
    'Cultsport(15)',
    'COTTON ON(14)',
    'Chkokko(10)',
    'CHROME & CORAL(5)',
    'CHILL WINSTON(5)',
    'Crocodile(4)',
    'Converse(4)',
    'Columbia(3)',
    'Chennis(3)',
    'CAPTAIN AMERICA(2)',
    'Calvin Klein(2)',
    'ColorPlus(1)',
    'CHE GUEVARA(1)',
    'CAMLA(1)',
    'DC(31)',
    'Difference of Opinion(27)',
    'DILLINGER(26)',
    'Duke(20)',
    'Dexter by Kook N Keech(6)',
    'Denizen From Levis(5)',
    'Deadpool(4)',
    'Disrupt(3)',
    'DEIN KLEIDER(2)',
    'DC Comics(2)',
    'Dollar Bigboss(1)',
    'Dawn of Justice(1)',
    'ether(55)',
    'Ecko Unltd(32)',
    'Ed Hardy(24)',
    'ESPRIT(16)',
    'ELABORADO(1)',
    'einstein(1)',
    'Flying Machine(137)',
    'Free Authority(73)',
    'French Connection(71)',
    'Friskers(36)',
    'FC Barcelona(17)',
    'FOREVER 21(15)',
    'FUGAZEE(14)',
    'Forca(13)',
    'FIDO DIDO(10)',
    'Fame Forever by Lifestyle(8)',
    'Force NXT(7)',
    'FILA(7)',
    'FIFA U-17 WC(6)',
    'Fort Collins(5)',
    'FITUP LIFE(4)',
    'FiTZ(3)',
    'Fruit of the loom(2)',
    'Fitkin(2)',
    'FRITZBERG(1)',
    'Globus(56)',
    'Game of Thrones by Kook N Keech(38)',
    'GAP(25)',
    'GRITSTONES(21)',
    'GRIFFEL(12)',
    'GAS(9)',
    'Genx(7)',
    'Game Of Thrones(4)',
    'GIORDANO(3)',
    'GUESS(2)',
    'Global Republic(2)',
    'GHPC(2)',
    'GESPO(2)',
    'Guns & Roses(1)',
    'Genius18(1)',
    'HERE&NOW(172)',
    'HRX by Hrithik Roshan(121)',
    'Huetrap(120)',
    'hummel(43)',
    'Hypernation(38)',
    'HIGHLANDER(21)',
    'Harvard(19)',
    'Harley-Davidson(12)',
    'H&M(7)',
    'Harry Potter(4)',
    'Hulk(1)',
    'Hue Men(1)',
    'Indian Terrain(12)',
    'INVICTUS(9)',
    'IMPACKT(9)',
    'Invincible(8)',
    'IMYOUNG(3)',
    'Iron Man(1)',
    'Jack & Jones(78)',
    'Justice League(56)',
    'Johnny Bravo by Kook N Keech(6)',
    'JUMP USA(3)',
    'Joker(3)',
    'Joven(2)',
    'John Players(2)',
    'Jimi Hendrix(1)',
    'Kook N Keech Marvel(103)',
    'Kook N Keech(71)',
    'Kook N Keech Disney(27)',
    'KULTPRIT(23)',
    'Killer(18)',
    'Kalt(11)',
    'Kook N Keech Star Wars(9)',
    'Kook N Keech Garfield(6)',
    'Kook N Keech Batman(6)',
    'Kappa(6)',
    'KROSSSTITCH(2)',
    'Kenneth Cole(2)',
    'Kryptic(1)',
    'Kook N Keech Music(1)',
    'Kook N Keech Archie(1)',
    'Levis(49)',
    'LOCOMOTIVE(41)',
    'Louis Philippe Jeans(19)',
    'Lee(18)',
    'Le Bison(12)',
    'LA LOFT(9)',
    'Lion King(7)',
    'Lotto(5)',
    'Leo Sansini(5)',
    'Louis Philippe Ath.Work(4)',
    'Lee Cooper(4)',
    'LINKIN PARK(1)',
    'Moda Rapido(192)',
    'Marvel Avengers(103)',
    'Maniac(34)',
    'Mast & Harbour(32)',
    'Marvel Spiderman(20)',
    'Mufti(13)',
    'Masculino Latino(11)',
    'Minions by Kook N Keech(7)',
    'Mr Bowerbird(6)',
    'Masch Sports(5)',
    'Monte Carlo(4)',
    'MANGO MAN(4)',
    'MTV(3)',
    'Metronaut(3)',
    'Marvel(3)',
    'Music(2)',
    'Marvel Comics(2)',
    'Mickey & Friends(1)',
    'Marks & Spencer(1)',
    'Nike(165)',
    'NBA(118)',
    'next(15)',
    'Numero Uno(3)',
    'Nirvana(1)',
    'New Balance(1)',
    'ONLY & SONS(35)',
    'oneliner(27)',
    'OVS(22)',
    'OFF LIMITS(8)',
    'Okane(7)',
    'Omtex(4)',
    'one8 x PUMA(3)',
    'OBOW(3)',
    'Puma(508)',
    'Proline Active(56)',
    'People(44)',
    'PUNK(31)',
    'Pepe Jeans(25)',
    'Parx(11)',
    'plusS(8)',
    'Polo Ralph Lauren(6)',
    'Peter England Casuals(6)',
    'PERFKT-U(5)',
    'Punisher(3)',
    'Peter England(3)',
    'Park Avenue(3)',
    'Proline(1)',
    'Roadster(372)',
    'Reebok(78)',
    'Rex Straut Jeans(33)',
    'Redwolf(24)',
    'Reebok Classic(22)',
    'Rigo(17)',
    'Red Tape(13)',
    'rock.it(5)',
    'Rodzen(3)',
    'Roadster Fast and Furious(3)',
    'Riot(2)',
    'Replay(2)',
    'RUF & TUF(1)',
    'Royal Enfield(1)',
    'REALM(1)',
    'RDSTR(1)',
    'SKULT by Shahid Kapoor(71)',
    'Superdry(56)',
    'SPYKAR(40)',
    'SINGLE(33)',
    'Status Quo(31)',
    'STAR WARS(30)',
    'Space Culture(28)',
    'Seven Rocks(11)',
    'Sweet Dreams(10)',
    'Smiley World(10)',
    'SHELTR(10)',
    'SF JEANS by Pantaloons(10)',
    'Soul Space(9)',
    'Solly Sport(7)',
    's.Oliver(7)',
    'Sztori(6)',
    'Superman(6)',
    'SWISS MILITARY(5)',
    'Steenbok(5)',
    'Solly Jeans Co.(5)',
    'SELECTED(5)',
    'Slub(4)',
    'SUICIDE SQUAD(3)',
    'Splash(1)',
    'Speedo(1)',
    'Simpsons(1)',
    'SEVEN by MS Dhoni(1)',
    'SDL by Sweet Dreams(1)',
    'Scotch & Soda(1)',
    'SayItLoud(1)',
    'Salomon(1)',
    'Tommy Hilfiger(63)',
    'Timberland(10)',
    'The Dry State(9)',
    'The Humbl Co.(6)',
    'Tinted(4)',
    'The Indian Garage Co(4)',
    'THE BEAR HOUSE(4)',
    'The North Face(3)',
    'True Blue(2)',
    'T-Tog(2)',
    'Threadless(1)',
    'United Colors of Benetton(65)',
    'UNDER ARMOUR(42)',
    'U.S. Polo Assn. Denim Co.(21)',
    'U.S. Polo Assn.(8)',
    'Unisopent Designs(6)',
    'Urbano Fashion(4)',
    'UCLA(4)',
    'Undercolors of Benetton(1)',
    'VIMAL JONNEY(32)',
    'VIMAL(7)',
    'V Dot(2)',
    'Voi Jeans(1)',
    'Van Heusen Sport(1)',
    'WROGN(153)',
    'Wear Your Mind(57)',
    'Wrangler(33)',
    'Wildcraft(28)',
    'Wolfpack(5)',
    'WILD WEST(5)',
    'WITH(4)',
    'WEXFORD(3)',
    'YWC(27)',
    'Young Trendz(24)',
    'Yuuki(12)',
    'YAK YAK(5)',
    'ZALLEN(4)',
    'Zeven(3)',
    'zebu(1)'];

export const PRICE_RANGE = [
    'Rs. 209 to Rs. 2257(39251)',
    'Rs. 2257 to Rs. 4305(1334)',
    'Rs. 4305 to Rs. 6353(24)',
    'Rs. 4778 to Rs. 6301(2)'
];

export const SEARCHED_ITEM_TYPES = {
    'Bundles' : ['Bundles', 'Single Styles'],
    'Fabric' : ['Bamboo', 'Blended', 'Cotton', 'Elastane','Linen'],
    'Fit' : ['Boxy', 'Compression', 'Loose', 'Regular Fit', 'Slim Fit'],
    'Length' : ['Crop', 'Longline', 'Regular'],
    'Multipack Set' : ['2', '3', '4', '5 And Above', 'Single'],
    'Neck' : ['Boat Neck', 'Cowl Neck', 'Halter Neck', 'Henley Neck', 'High Neck'],
    'Occasion' : ['Casual', 'Party', 'Sports', 'Work'],
    'Pattern' : ['Checked', 'Colourblocked', 'Dyed', 'Printed', 'Self Design'],
    'Pattern Converage' : ['All-Over', 'Back', 'Chest', 'Full-Front', 'Placement'],
    'Print or Pattern Type' : ['Abstract', 'Biker', 'Camouflage', 'Checked', 'Colourblocked'],
    'Size' : ['3xl', '3xs', '4xl', '5xl', '6xl', '7xl', '8xl', 'L', 'M', 'S', 'S/M', 'Xl', 'Xl/Xxl', 'Xs', 'Xxl', 'Xxs'],
    'Sleeve Length' : ['Long Sleeves', 'Short Sleeves', 'Sleeveless', 'Three-Quater'],
    'Sport' : ['Badminton', 'Baseball', 'Basketball', 'Cricket', 'Football']
};

export const SEARCHED_RESULTS = [
    {
      'src': '../assets/images/boss_green_solid_round.webp',
      'title': 'BOSS Green',
      'itemDescription': 'Solid Round Neck T-shirt',
      'sizes': 'X, M, XL, XS',
      'discountedPrice': '8400',
      'actualPrice': '12000',
      'dicountOffered': '30'
    },
    {
      'src': '../assets/images/boss_green_printed_round.webp',
      'title': 'BOSS Green',
      'itemDescription': 'Printed Round Neck T-shirt',
      'sizes': 'X, M, XL, XS',
      'discountedPrice': '6400',
      'actualPrice': '8000',
      'dicountOffered': '20'
    },
    {
      'src': '../assets/images/puma_printed.webp',
      'title': 'PUMA',
      'itemDescription': 'Printed T-shirt',
      'sizes': 'X, M, XL, XS',
      'discountedPrice': '6299',
      'actualPrice': '6999',
      'dicountOffered': '10'
    }
  ];